### ISSUE TITLE
change setup.py to use io.open with encoding='utf-8' everywhere

### ISSUE THREAD

**Issue by alex-smirnov** [morepath/morepath#286] opened 2015-01-06 13:17 UTC
Can't install more.transaction on python 3.4 on my Mac
```
Collecting more.transaction
  Using cached more.transaction-0.3.zip
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/nv/m228t1b10dvd28l2190qhrnr0000gn/T/pip-build-gyiw600q/more.transaction/setup.py", line 7, in <module>
        open('CHANGES.txt').read())
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 223: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/var/folders/nv/m228t1b10dvd28l2190qhrnr0000gn/T/pip-build-gyiw600q/more.transaction/setup.py", line 7, in <module>
    
        open('CHANGES.txt').read())
    
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/encodings/ascii.py", line 26, in decode
    
        return codecs.ascii_decode(input, self.errors)[0]
    
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 223: ordinal not in range(128)
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /var/folders/nv/m228t1b10dvd28l2190qhrnr0000gn/T/pip-build-gyiw600q/more.transaction
```
Default encoding when open file with function open() is 'ascii'.
I think must be open('CHANGES.txt', encoding='utf-8')

**Comment by href** [comment] 2015-01-06 13:23
This might well be because of my name in the CHANGELOG:
https://github.com/morepath/more.transaction/commit/372f1255549ea07ee5b42d9300321ff7f8d6fba2
;)

However, I cannot reproduce the issue here (I use Python 3.4.2).
Both installing through pip and using the HEAD with setup.py develop work.

I'm running this in a virtualenv, though I don't think that would matter.

**Comment by faassen** [comment] 2015-01-06 13:32
The explanation for the differences seems to be this behavior:

```
encoding is the name of the encoding used to decode or encode the file. This should only be used in text mode. The default encoding is platform dependent (whatever locale.getpreferredencoding() returns), but any encoding supported by Python can be used. See the codecs module for the list of supported encodings.
```

I think this kind of locale dependent behavior is not a good idea in Python, but we can't fi that, so I'll hardcode a 'utf-8' in the hope it fixes things.

@href, who uses umlauts in a name anyway. I suggest you change it so we can close this bug. :) (happy new year!)

**Comment by faassen** [comment] 2015-01-06 13:36
Argh, for extra polyglot entertainment the Python 2 open() function does not accept an encoding argument... @href, any suggestions better than opening with rb and then doing a unicode call for utf8? It sucks we can't refer to some kind of utility function for this in setup.py; this forces us to add more cruft to all of them.

**Comment by href** [comment] 2015-01-06 13:46
Well the easiest way would be to simply change "Krienbühl" to "Krienbuehl", tbh. It's the ASCII way of writing my name (and the only sure way to get through every possible hotel/flight ticket booking system).

Happy new year!

**Comment by alex-smirnov** [comment] 2015-01-06 13:53
Right now I can't use tox for testing, because more.transaction not installed from pypi automatically

**Comment by faassen** [comment] 2015-01-06 13:54
Until the next time I drop in an umlaut into a changelog. I just found out there's an io.open in Python 2 that does allow an encoding argument. I've modified the core Morepath setup.py just now and I'll do it for more.transaction now. We need to do this for all the setup.py's though.

**Comment by faassen** [comment] 2015-01-06 14:31
Okay, I've released more.transaction 0.4 which hopefully makes this go away. @alex-smirnov, please let me know!

I've also taken the opportunity to rename the preferred name of what you import from transaction_app to TransactionApp and I've updated the morepath_sqlalchemy example accordingly

**Comment by alex-smirnov** [comment] 2015-01-06 14:53
Thanks! Now everything ok!

**Comment by faassen** [comment] 2015-01-06 14:56
Renaming this issue to track this for other extensions such as more.static and more.forwarded until all their setup.py's are updated. Volunteers: just look at more.transaction's use of open for examples.

**Comment by taschini** [comment] 2016-05-04 07:36
I used the list in #302, extended with the repositories in the `[sources]` sections of their buildout.cfg, and updated their ``setup.py`` using more.transaction as a template.

While there I updated the ``setup.py`` files to be flake8 compliant:
* In most cases just blank space edits (spaces around equal signs in argument lists and indentation).
* Occasionally, I removed an unused import.

**Comment by faassen** [comment] 2016-05-04 10:24
Thanks, should be all merged now!

**Closed by faassen** 2016-05-04 10:24 UTC
Labels: entry level, help wanted
