### ISSUE TITLE
Can't get morepath to scan other modules correctly

### ISSUE THREAD

**Issue by aplavin** [morepath/morepath#345] opened 2015-09-01 19:10 UTC
Currently I'm trying to follow the "Organizing your project" section of the documentation and put paths and views definitions outside of the main module. However, I'm unable to actually make it working. My project directory structure currently looks like this:

    myproject
        setup.py
        myproject
            __init__.py
            main.py
            paths.py

Where `setup.py` contains `packages = ['myproject']`, `main.py' sets up and runs morepath:

    import morepath
    from werkzeug.serving import run_simple
    
    class App(morepath.App):
        pass
    
    def main():
        morepath.autosetup()
        run_simple('localhost', 5000, App(), use_reloader=True, use_debugger=True)
    
    if __name__ == '__main__':
        main()
and `paths.py` contains both a path and a view:

    from main import App
    
    class Overview(object):
        pass
    
    @App.path(model=Overview, path='/')
    def overview():
        return Overview()
    
    @App.json(model=Overview)
    def json_view(self, request):
        return {}

When I run it like `python main.py` and try to access the `/` url, I get an `reg.error.KeyExtractorError` (traceback:

    Traceback (most recent call last):
      File "... virtualenv .../lib/python3.4/site-packages/morepath/app.py", line 142, in __call__
        response = self.publish(request)
      File "... virtualenv .../lib/python3.4/site-packages/morepath/publish.py", line 71, in publish
        return resolve_response(request, model)
      File "... virtualenv .../lib/python3.4/site-packages/morepath/publish.py", line 46, in resolve_response
        view = generic.view.component(request, obj, lookup=request.lookup)
      File "... virtualenv .../lib/python3.4/site-packages/reg/dispatch.py", line 58, in component
        return get_lookup(kw).component(self.wrapped_func, *args, **kw)
      File "... virtualenv .../lib/python3.4/site-packages/reg/registry.py", line 424, in component
        key = self.key_lookup.predicate_key(callable, *args, **kw)
      File "... virtualenv .../lib/python3.4/site-packages/reg/registry.py", line 223, in predicate_key
        raise KeyExtractorError()    
). I tried several other things, like doing the scanning manually before running:

    config = morepath.setup()
    import paths
    config.scan(paths)
    config.scan()
    config.commit()

but in this case I get a 404 error. However, everything works correctly if I move the definitions from `paths.py` to `main.py`.

How to fix this, what's the correct way?

**Comment by href** [comment] 2015-09-02 08:38
I'm not spotting an obvious error so I'd like to have a look at your code. Can you upload it somewhere so can run it locally?

**Comment by faassen** [comment] 2015-09-02 15:35
One difference in what you do and the document described is how you start things. You use

`python main.py`

presumably from within the `myproject` package. The document uses a `setup.py` entry point.

It may that this is what confuses the scanning logic, as you start the project from within its package, so Python cannot find it to import it.

You could try going to the project directory and typing:

`python myproject/main.py`

and see whether that helps.

If this causes the problem, I think we need to add a sidebar or something to that document to talk about this stuff.

**Comment by aplavin** [comment] 2015-09-03 09:53
__faassen__, when I use the `setup.py` entry point, this actually works! But both `python main.py` and `python myproject/main.py` don't... Can this be fixed, or is it by design? Personally I prefer the way decorators work in Flask, for example: the modules with decorators should just be imported, and then everything works. And what's the reason behind this part of morepath implementation? Why is extra scanning needed, after I `import` the modules which specify `App.path`s, `App.view`s and so on? In this case the decorators are executed and they can record all the required information themselves. This, as I understand, should also simplify morepath code, as scanning would not be needed.

**Comment by faassen** [comment] 2015-09-03 11:45
@aplavin, glad it works with the entry point. I would like to get the cases you try to work somehow, but we need to debug it first to see why they're failing; it's not immediately obvious.

Good question about why scanning at all. The reason scanning is used instead of a direct system like Flask is three-fold:

* a direct system like Flask requires configuration to be resolved during import time, and this can lead to problems; it's really too early to do configuration. See a description here: http://docs.pylonsproject.org/projects/pyramid/en/latest/designdefense.html#application-programmers-don-t-control-the-module-scope-codepath-import-time-side-effects-are-evil

* Morepath actually needs the whole configuration state in order to do some of its more advanced stuff, both overrides and conflict detection. App B may derive from app A, and a view in app B can override a view in app A. Also: some configurations really need to run earlier than others; if you add a new view predicate it needs to be registered before views in that application are used -- with import order, the application developer would have to know about that kind of stuff.

* If you wouldn't do scanning, you would *have* to import modules that you want registered. That's kind of weird, as the only reason you do an import is to trigger configuration registration, not actually because you want to use anything from it. So you'd have a thing like this somewhere "import .view" and then you don't use anything from `view` in that module, something pyflakes for instance will say is an unused import. Consider a complicated application where you have an extension package that extends a core package -- you'd have to make not only sure you depend on the extension in your application, but also to import the right stuff from it to make it really do its stuff.

Unfortunately there is a tradeoff: we get all these features and are able to do powerful reason about configuration, but the initial setup of an application is more difficult as it requires scanning. I hope we can eliminate the remaining gotchas.

@href, we need to debug this -- if it turns out to be hard to solve, we need to add some documentation. Do you have any idea what might cause it to fail when you run things by hand from python?

**Comment by aplavin** [comment] 2015-09-03 12:12
@faassen, now I kinda see the reasons behind this, and cases when they may actually be useful... But when one wants just a relatively simple and small application the design decisions make development (and running) more difficult. Also it feels like re-implementing a part of already existing python functionality, and too much abstraction sometimes (more on this below). But as for me, it would be nice if at least manual scanning (like `config.scan()`, `config.scan(paths)`... in my first example) worked correctly, as this is similar to the way such things are done in Flask (which is popular).

I tried debugging the problem myself before posting here, but there are things that were hard to understand. I mean things like all the `config.configurables` arrays and `action.configurable` objects, the latter being not in the former, many not-so-obvious redirections, and similar. In the end I couldn't find the reason why in my case all the decorators were in fact scanned, but their `action.configurable` was not in `config.configurables`, which is probably the reason of my example not working (the case with 404 error).

**Comment by href** [comment] 2015-09-03 13:23
> Do you have any idea what might cause it to fail when you run things by hand from python?

To me it seems to be a bug in the configuration scanning logic. I am able to reproduce this problem, though I haven't yet found the reason. I found out a few interesting things though:

* `autosetup` won't work because it scans installed packages for modules.
* if `config.scan()` in the example above is replaced with `import main; config.scan(main)` it works!
* If we leave `config.scan()` as it is, the prepare step of the action is executed, but *not* the perform step. So it's kind of scanned, but it somehow doesn't end in any of the configurations which are executed during `commit`.

**Comment by href** [comment] 2015-09-03 14:00
I'm beginning to suspect this has something to do with the special status of the `__main__` module in python. When providing no value to `config.scan()` the `__main__` module is going to be scanned. I don't know why this is a problem but the `__main__` module's special status leads to weird things when it comes to globals. 

If we can get `caller_package` to return the `main` module instead of the `__main__` module in this case, the bug will go away. Having a runner script in a separate file which imports and scans everything it needs is a workaround for this problem.

**Comment by href** [comment] 2015-09-03 14:49
This is how main.py has to look like for it to work:

```python
import morepath
from werkzeug.serving import run_simple

class App(morepath.App):
    pass

def main():
    config = morepath.setup()

    import main
    import paths
    config.scan(main)
    config.scan(paths)
    config.commit()

    run_simple('localhost', 5000, main.App(), use_reloader=True, use_debugger=True)

if __name__ == '__main__':
    main()

```

Note how I even use `main.App` to instantiate the application and not `App` which also fails. This is really an issue of __main__ as `id(App)` is different from `id(main.App)`. Not sure how or if we can solve this.

**Comment by href** [comment] 2015-09-04 07:49
Ok I think I'm starting to get the hang of this. The registry for App is created two times (by `AppMeta.__new__`). Once when running `main.py` and once when importing `App` from `paths.py`. 

Basically every time the interpreter encounters `class App(morepath.App)`, it creates a new type object with a new registry. This happens twice in our case because we use the class directly in main and we import it in paths. We think we use the same class with the same registries, but we're actually not (that is, we use two classes which share the same definition, but which are two different objects in memory).

To fix this we would have to somehow share our registries between these classes. I don't think that can be done and I doubt it's a sane thing to do. A way easier fix would be to just define the Application in a different module than the code that runs it.

So we can either have application, paths and so on in one file (like in our very simple examples). Or we can have a more complex setup where the application is defined in it's own module. Basically, this would be a good layout for @aplavin's original example:

* `__init__.py`
* `app.py`
   ```python
  import morepath

  class App(morepath.App):
    pass
   ```
* `paths.py`
  ```python
  from app import App

  class Overview(object):
      pass

  @App.path(model=Overview, path='/')
  def overview():
      return Overview()
      
  @App.json(model=Overview)
  def json_view(self, request):
      return {}
  ```
* `run.py`
  ```python
  import morepath
  import app
  import paths

  from werkzeug.serving import run_simple

  if __name__ == '__main__':
      config = morepath.setup()
      config.scan(app)
      config.scan(paths)
      config.commit()

      run_simple('localhost', 5000, app.App(), use_reloader=True, use_debugger=True)

  ```

**Comment by faassen** [comment] 2015-09-08 09:29
@aplavin, concerning the configuration system, I'm not sure what of it is implementing functionality that's in Python already? Could you specify a bit more?

The insides of the configuration engine are ripe for refactoring, as they've grown as I needed more features in Morepath. They were driven by real concerns in Morepath step by step, which explains why they are somewhat convoluted now.

**Comment by faassen** [comment] 2015-09-08 09:35
Thanks for all that research, @href! I think this duplication of objects is related to why plain decorators will lead to problems too. What you've done in your example is just scan every module manually, so that will work. We can't get package scanning to work?

The question is now how we move on from here. One recommendation could be that the code that scans stuff and starts the server should *not* contain anything scannable itself. Though I'd still be good if we could scan the whole package. An alternative recommendation could be to always get people to use entry points to start the application. I also wonder whether there is a way to *detect* this kind of misconfiguration and then immediately report on it?

**Comment by href** [comment] 2015-09-08 10:03
> Thanks for all that research, @href! I think this duplication of objects is related to why plain decorators will lead to problems too. What you've done in your example is just scan every module manually, so that will work. We can't get package scanning to work?

Welcome ;) - I didn't really look into package scanning, because I was trying out the example before it was a package (as in, I just tested this out in a plain folder). For fully automated scanning we require an installed package.

> The question is now how we move on from here. One recommendation could be that the code that scans stuff and starts the server should not contain anything scannable itself. Though I'd still be good if we could scan the whole package. An alternative recommendation could be to always get people to use entry points to start the application. I also wonder whether there is a way to detect this kind of misconfiguration and then immediately report on it?

The recommendation makes sense to me, because we really can't solve this as far as I'm concerned. Unless we put the registry somewhere global, outside the actual application class. I don't think we want that. We could keep track of the created registries and possibly have some kind of warning. But that's just a guess. Maybe it won't work.

I think we've encountered some kind of gap in the Morepath learning curve. You start out with single file examples, which work great and are pure python code. You then want to start moving pieces of that single file into other files, at which point you really should already be using a proper package.

I'm not crazy about boilerplate setup scripts (because it just indicates you have too much boilerplate). But maybe having one wouldn't be such a bad idea here. Say a cookie-cutter template. At least as an easy way of getting started with a proper morepath project.

**Comment by faassen** [comment] 2015-09-08 10:43
So we need to update the docs somewhere to point out these things. We need to do it in quickstart I think, and in "how to organize your project". Anywhere else?

Yeah, I think at the very least a demo boilerplate, or a script that sets up a project according to "how to organize your project" would be good. We have an issue for that somewhere. (I agree completely with you about such things being a risk of just accepting the boilerplate instead of actively working to get rid of it)

**Comment by href** [comment] 2015-09-08 10:49
> So we need to update the docs somewhere to point out these things. We need to do it in quickstart I think, and in "how to organize your project". Anywhere else?

I think that's it.

**Comment by faassen** [comment] 2015-09-08 10:54
Do you want to give a shot at writing this bit? You understand the scenarios better than I do. Though in the text we should tell the developer what to do first, and leave complicated explanations to later or not at all.

**Comment by href** [comment] 2015-09-08 11:13
Sure, but it'll have to wait for at least next week. I'm a bit preoccupied at the moment.

**Comment by href** [comment] 2015-09-18 11:52
Without mentioning why yet I split up main.py into app.py/run.py.. What do you think?
https://github.com/morepath/morepath/commit/978f3e0a112a397a18284580dda8a2a3f62ac4da

I feel like that might be a good recommended layout, because it leaves room for adding more advanced things like custom directives/tweens to the app.py and to extend run.py with configuration loading. This is what I personally do - I keep the application and the running of it strictly separate.

I'll add the info about why Morepath *requires* this separation into an aside.

**Comment by href** [comment] 2015-09-18 11:54
There are some other places where I would have to change main to app if this makes sense.

**Comment by href** [comment] 2015-09-21 07:22
Instead of run.py we could also use __main__.py. This might be more pythonic, but it would introduce an extra concept to explain.

**Comment by href** [comment] 2015-09-29 08:11
@fassen What do you think about the way I want to split main.py? If this is okay with you I can complete this ticket ;)

**Comment by faassen** [comment] 2015-10-01 09:47
Sorry, I haven't paid enough attention to this! I think splitting it up is okay. I think I didn't call it `app.py` before as it conflicted with the lowercase `app` objects we have in Morepath, but that issue went away as we went to app classes.

**Comment by gnimmelf** [comment] 2015-11-23 15:05
Hi all, sorry to co-opt this issue, but

Just starting out with morepath, and being more or less a setuptools/wsgi-newbie, I have no idea how to actually even start the application from the command-line using `python setup.py [...]`. There is so much heavy documentation for both setuptools and wsgi, that google hasn't shown me the way yet (I'm lazy!). 

Maybe it would be a good idea just to include a section in the documentation on various ways to run an `entry_point`. The only one working for me now is `setup.py install`, then cmd-line the `entry-point`-name (which tells you how a newbie I am), but I cannot get that to work with the reloader...

Otherwise I am really looking forward to morepath. I loved the Zope ideas, but in the end the product just got too heavy all those years ago.

Cheers!

**Comment by href** [comment] 2015-11-23 15:43
@gnimmelf Sounds like you got quite far already :)

Is your code online somewhere? I can have a look and see why the reloading doesn't work.
Also, if you don't mind do create a new issue about your trouble with entry-points. This issue is about config scanning - a problem which you don't seem to have.

**Comment by gnimmelf** [comment] 2015-11-23 16:29
@href the reason I put it here was because I got an similar error to the one mentioned above (on a registry lookup) when running `__main__` from the command-line. I can't remember what state my code was in that produced that error, but if I see it again, I'll post it here.

Also, I'll make a new issue for my `setup.py install` inquiry.

Cheers!

**Comment by gnimmelf** [comment] 2015-11-24 21:21
Oki, I got it working by actually reading stuff properly instead of just skimming through (really, who actually does that anymore?)

The solution is to have `main.py` one "pakage-level" above the actual app-code, and have `main.py contain only the "runner". 

That makes three levels, "myproject":[`setup.py`] -> "blog":[`main.py`] -> "app":[`app.py`, ...], and then in "app" I can start working with files again, vs packages.

Is this what you guys meant?

**Comment by href** [comment] 2015-11-25 08:45
> That makes three levels, "myproject":[setup.py] -> "blog":[main.py] -> "app":[app.py, ...], and then in "app" I can start working with files again, vs packages.
>
> Still have to manually scan tho =(

You got that right and you seem to be doing everything right in your repository. `morepath.autosetup` works just as it should in your case. Is this the manual scanning you are talking about?

The main point is this: Keep the code which *runs* your morepath app in a different file than the file(s) which *define* your morepath app. That's not always necessary, but if you follow this rule you will avoid common pitfalls posed by the configuration mechanism.

So just have a main.py/run.py like you do and only keep run code in there. That's it.

**Comment by faassen** [comment] 2016-04-04 09:47
Since we have dectate now and no more venusian this should be mitigated quite a bit. So closing this until we get new reports of confusion.

**Closed by faassen** 2016-04-04 09:47 UTC
Labels: bug, documentation
