### ISSUE TITLE
a WSGI setup documentation page

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#169] opened 2014-07-08 13:52 UTC
See here for what Flask does. http://flask.pocoo.org/docs/deploying/wsgi-standalone/

**Comment by faassen** [comment] 2016-04-18 12:38
Someone who has no particular experience with Morepath internals could still write this, so marking this entry level.

**Comment by href** [comment] 2016-09-07 09:09
This seems to be a duplicate of #205 to some extent, so let's close this ticket in favour of the other one.

**Closed by href** 2016-09-07 09:09 UTC
Labels: documentation, entry level, help wanted
